### ISSUE TITLE
The readme should be more explicit about the dependencies

### ISSUE THREAD

**Issue by dgmstuart** [dxw/contracts#4]
Clearly some versions of Ruby and bundler are required. The readme should probably specify this and say/linkto how to install bundler, maybe also how to install ruby/rubygems on Windows? Does Ruby/rubygems come pre-installed on most linux distros?

Also does this really work with *any* version of kramdown? Maybe that's a separate issue

**Comment by harry-m** [comment]
I've added a bit more detail to the readme, but I don't know enough about Windows users to be able to add that much detail - and not sure it's proportionate to the need. 

See f6819641f0997961451c71d9f0b7c4bd6deaad9d.
